#!/usr/bin/env bash
# Task 3. Redirection
apt-get update;
apt-get install nginx -y;
service nginx start;

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=AzRR1Dqd2kE/;
     }
     }
" > /etc/nginx/sites-available/default;
service nginx restart;
