#!/usr/bin/env bash
# Task 0. Double the number of webservers
apt-get update;
apt-get install nginx -y;
service nginx start;
mkdir /var/www/html;
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html;
echo "Ceci n'est pas une page" > /var/www/html/404.html;

printf %s "server {
     listen      80;
     listen      [::]:80;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=AzRR1Dqd2kE/;
     }
     location / {
           add_header X-Served-By '$HOSTNAME';
           error_page 404 /404.html;
     }
}" > /etc/nginx/sites-available/default;
service nginx restart;