#!/usr/bin/env bash
# Task 0. Nginx likes port 80
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     }
}" > /etc/nginx/sites-available/default;
service nginx restart;
