#!/usr/bin/env bash
# Task 1. Run Nginx as Nginx
chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
